"""empty message

Revision ID: 158d509fd120
Revises: 16be38651d87
Create Date: 2024-12-04 08:19:24.083014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158d509fd120'
down_revision = '16be38651d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('dummy_id', sa.Integer(), nullable=False),
    sa.Column('date_of_creation', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('dummy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy')
    # ### end Alembic commands ###
