"""empty message

Revision ID: 16be38651d87
Revises: 730c7e50ea51
Create Date: 2024-12-03 22:30:40.810150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16be38651d87'
down_revision = '730c7e50ea51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_artwork',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.artwork_id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.auction_id'], ),
    sa.PrimaryKeyConstraint('auction_id', 'artwork_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_artwork')
    # ### end Alembic commands ###
