"""Add curator_id to auction

Revision ID: 29804d4433a5
Revises: f02d17fa7b4d
Create Date: 2024-12-03 10:58:08.535013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29804d4433a5'
down_revision = 'f02d17fa7b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'curator', ['curator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('curator_id')

    # ### end Alembic commands ###
