"""empty message

Revision ID: 6713c6327833
Revises: 158d509fd120
Create Date: 2024-12-04 08:50:23.238747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6713c6327833'
down_revision = '158d509fd120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.drop_column('auction_name')

    # ### end Alembic commands ###
