"""Initial migration

Revision ID: 730c7e50ea51
Revises: 29804d4433a5
Create Date: 2024-12-03 22:19:26.504293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730c7e50ea51'
down_revision = '29804d4433a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('artwork_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('artwork',
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('artwork_title', sa.String(length=100), nullable=False),
    sa.Column('artwork_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('date_of_creation', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('artwork_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('notification_date', sa.DateTime(), nullable=True),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('auction',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('starting_price', sa.Float(), nullable=True),
    sa.Column('auction_status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('current_highest_bid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.artwork_id'], ),
    sa.PrimaryKeyConstraint('auction_id')
    )
    op.create_table('auction_artwork',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.artwork_id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.auction_id'], ),
    sa.PrimaryKeyConstraint('auction_id', 'artwork_id')
    )
    op.create_table('bid',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('bid_date_time', sa.DateTime(), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('bidder_names', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.artwork_id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.auction_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')
        batch_op.drop_column('artist_name')

    op.drop_table('bid')
    op.drop_table('auction_artwork')
    op.drop_table('auction')
    op.drop_table('notification')
    op.drop_table('artwork')
    op.drop_table('category')
    # ### end Alembic commands ###
