"""Initial migration

Revision ID: f02d17fa7b4d
Revises: 
Create Date: 2024-12-03 08:26:28.058513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f02d17fa7b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('user')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'admin'"))

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'artist'"))

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_constraint('artwork_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('artwork_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['artist_id'])
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['category_id'])

    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.drop_constraint('auction_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artwork', ['artwork_id'], ['artwork_id'])

    with op.batch_alter_table('auction_artwork', schema=None) as batch_op:
        batch_op.drop_constraint('auction_artwork_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('auction_artwork_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artwork', ['artwork_id'], ['artwork_id'])
        batch_op.create_foreign_key(None, 'auction', ['auction_id'], ['auction_id'])

    with op.batch_alter_table('curator', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'customer'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'customer'"))

    with op.batch_alter_table('curator', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('auction_artwork', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auction_artwork_ibfk_1', 'auction', ['auction_id'], ['auction_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('auction_artwork_ibfk_2', 'artwork', ['artwork_id'], ['artwork_id'], ondelete='CASCADE')

    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auction_ibfk_1', 'artwork', ['artwork_id'], ['artwork_id'], ondelete='CASCADE')

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('artwork_ibfk_1', 'artists', ['artist_id'], ['artist_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('artwork_ibfk_2', 'category', ['category_id'], ['category_id'], ondelete='CASCADE')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'artist'"))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'admin'"))

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
